-- =============================================
-- Dutch Pet Names Seed Data (Corrected)
-- Manually reviewed and categorized
-- =============================================

-- =============================================
-- DUTCH (nl) - Cute & Sweet (Lief & Schattig)
-- Zachte klanken, warm gevoel, knuffelbaar
-- =============================================
INSERT INTO public.names (name, gender, set_id)
SELECT name, gender, (SELECT id FROM public.name_sets WHERE language = 'nl' AND style = 'cute' LIMIT 1)
FROM (VALUES
    ('Princess', 'female'),
    ('Whitney', 'female'),
    ('Bentley', 'neutral'),
    ('Charley', 'neutral'),
    ('Chelsea', 'neutral'),
    ('Pebbles', 'neutral'),
    ('Quinta', 'female'),
    ('Shanti', 'female'),
    ('Sheila', 'female'),
    ('Sienna', 'female'),
    ('Bonita', 'female'),
    ('Nikita', 'female'),
    ('Sascha', 'female'),
    ('Casper', 'male'),
    ('Floris', 'male'),
    ('Morris', 'male'),
    ('Bijoux', 'neutral'),
    ('Buddha', 'neutral'),
    ('Chanel', 'neutral'),
    ('Bailey', 'neutral'),
    ('Beauty', 'neutral'),
    ('Branco', 'neutral'),
    ('Bumper', 'neutral'),
    ('Buster', 'neutral'),
    ('Ceasar', 'neutral'),
    ('Cooper', 'neutral'),
    ('Dexter', 'neutral'),
    ('Disney', 'neutral'),
    ('Hailey', 'neutral'),
    ('Harley', 'neutral'),
    ('Kaylee', 'neutral'),
    ('Marley', 'neutral'),
    ('Mellow', 'neutral'),
    ('Mischa', 'neutral'),
    ('Muffin', 'neutral'),
    ('Murphy', 'neutral'),
    ('Nelson', 'neutral'),
    ('Quincy', 'neutral'),
    ('Quinty', 'neutral'),
    ('Scooby', 'neutral'),
    ('Shadow', 'neutral'),
    ('Shelby', 'neutral'),
    ('Smokey', 'neutral'),
    ('Snoopy', 'neutral'),
    ('Woezel', 'neutral'),
    ('Lilly', 'female'),
    ('Daisy', 'female'),
    ('Lieve', 'female'),
    ('Engel', 'female'),
    ('Bambi', 'neutral'),
    ('Dolly', 'neutral'),
    ('Molly', 'neutral'),
    ('Ginny', 'neutral'),
    ('Laila', 'neutral'),
    ('Layla', 'female'),
    ('Misty', 'neutral'),
    ('Teddy', 'neutral'),
    ('Winnie', 'neutral'),
    ('Yindi', 'female'),
    ('Prince', 'male'),
    ('Chicco', 'male'),
    ('Quinto', 'male'),
    ('Scotty', 'male')
) AS t(name, gender)
ON CONFLICT DO NOTHING;

-- =============================================
-- DUTCH (nl) - Pet Nicknames (Koosnamen)
-- Verkleinwoorden, troetelnamen, typisch NL
-- =============================================
INSERT INTO public.names (name, gender, set_id)
SELECT name, gender, (SELECT id FROM public.name_sets WHERE language = 'nl' AND style = 'petnicknames' LIMIT 1)
FROM (VALUES
    ('Floortje', 'female'),
    ('Saartje', 'female'),
    ('Fientje', 'female'),
    ('Beertje', 'neutral'),
    ('Prutske', 'neutral'),
    ('Roosje', 'female'),
    ('Loekie', 'female'),
    ('Binkie', 'neutral'),
    ('Bennie', 'neutral'),
    ('Guusje', 'neutral'),
    ('Harrie', 'neutral'),
    ('Pukkie', 'neutral'),
    ('Sammie', 'neutral'),
    ('Tommie', 'neutral'),
    ('Trixie', 'neutral'),
    ('Famke', 'female'),
    ('Femke', 'female'),
    ('Lotje', 'female'),
    ('Boyke', 'neutral'),
    ('Ukkie', 'neutral'),
    ('Pietje', 'neutral'),
    ('Nelly', 'female'),
    ('Boefje', 'neutral'),
    ('Dotje', 'neutral'),
    ('Snuffie', 'neutral'),
    ('Knuffie', 'neutral'),
    ('Schatje', 'neutral'),
    ('Liefje', 'neutral'),
    ('Rakker', 'neutral')
) AS t(name, gender)
ON CONFLICT DO NOTHING;

-- =============================================
-- DUTCH (nl) - Vintage / Nostalgisch
-- Ouderwetse namen, opa/oma stijl
-- =============================================
INSERT INTO public.names (name, gender, set_id)
SELECT name, gender, (SELECT id FROM public.name_sets WHERE language = 'nl' AND style = 'vintage' LIMIT 1)
FROM (VALUES
    ('Willem', 'male'),
    ('Truus', 'female'),
    ('Kobus', 'male'),
    ('Piet', 'male'),
    ('Cor', 'male'),
    ('Dorus', 'male'),
    ('Berend', 'male'),
    ('Miep', 'female'),
    ('Grietje', 'female'),
    ('Henk', 'male'),
    ('Kees', 'male'),
    ('Jan', 'male'),
    ('Fons', 'male'),
    ('Mien', 'female'),
    ('Sjaan', 'female'),
    ('Tinus', 'male'),
    ('Gerrit', 'male'),
    ('Aagje', 'female'),
    ('Betje', 'female'),
    ('Dirkje', 'female')
) AS t(name, gender)
ON CONFLICT DO NOTHING;

-- =============================================
-- DUTCH (nl) - Nature / Natuur
-- Planten, dieren, weer, elementen
-- =============================================
INSERT INTO public.names (name, gender, set_id)
SELECT name, gender, (SELECT id FROM public.name_sets WHERE language = 'nl' AND style = 'nature' LIMIT 1)
FROM (VALUES
    ('Storm', 'neutral'),
    ('Sunny', 'neutral'),
    ('Muis', 'neutral'),
    ('Vos', 'neutral'),
    ('Wolf', 'neutral'),
    ('Beer', 'neutral'),
    ('Maan', 'female'),
    ('Tijger', 'male'),
    ('Bliksem', 'neutral'),
    ('Sterre', 'female'),
    ('Pepper', 'neutral'),
    ('Ginger', 'neutral'),
    ('Poppy', 'female'),
    ('Snowy', 'neutral'),
    ('Dusty', 'neutral'),
    ('Fleur', 'female'),
    ('Terra', 'female'),
    ('Nova', 'female'),
    ('Luna', 'female'),
    ('Maple', 'neutral'),
    ('Willow', 'female'),
    ('Fern', 'female'),
    ('Ivy', 'female'),
    ('Sky', 'neutral'),
    ('Cloud', 'neutral'),
    ('Pluis', 'neutral')
) AS t(name, gender)
ON CONFLICT DO NOTHING;

-- =============================================
-- DUTCH (nl) - Funny / Grappig & Speels
-- Humor, eten, woordspelingen
-- =============================================
INSERT INTO public.names (name, gender, set_id)
SELECT name, gender, (SELECT id FROM public.name_sets WHERE language = 'nl' AND style = 'funny' LIMIT 1)
FROM (VALUES
    ('Boris', 'male'),
    ('Doedel', 'neutral'),
    ('Doerak', 'neutral'),
    ('Cookie', 'neutral'),
    ('Muffin', 'neutral'),
    ('Goofy', 'neutral'),
    ('Happy', 'neutral'),
    ('Dribbel', 'neutral'),
    ('Twister', 'neutral'),
    ('Skippy', 'neutral'),
    ('Speedy', 'neutral'),
    ('Sparky', 'neutral'),
    ('Spikey', 'neutral'),
    ('Stitch', 'neutral'),
    ('Dobber', 'neutral'),
    ('Droopy', 'neutral'),
    ('Chucky', 'neutral'),
    ('Chicky', 'neutral'),
    ('Deejay', 'neutral'),
    ('Danger', 'neutral'),
    ('Diablo', 'neutral'),
    ('Mickey', 'neutral'),
    ('Bandit', 'neutral'),
    ('Boomer', 'neutral'),
    ('Django', 'neutral'),
    ('Mazzel', 'neutral'),
    ('Bikkel', 'neutral'),
    ('Duvel', 'neutral'),
    ('Diezel', 'neutral')
) AS t(name, gender)
ON CONFLICT DO NOTHING;

-- =============================================
-- DUTCH (nl) - Classic / Klassiek
-- Tijdloze, populaire namen
-- =============================================
INSERT INTO public.names (name, gender, set_id)
SELECT name, gender, (SELECT id FROM public.name_sets WHERE language = 'nl' AND style = 'classic' LIMIT 1)
FROM (VALUES
    ('Diesel', 'neutral'),
    ('Bella', 'female'),
    ('Buddy', 'neutral'),
    ('Lucky', 'neutral'),
    ('Simba', 'neutral'),
    ('Lady', 'female'),
    ('Kira', 'female'),
    ('Sam', 'male'),
    ('Sem', 'male'),
    ('Max', 'male'),
    ('Milo', 'male'),
    ('Jack', 'male'),
    ('Rex', 'male'),
    ('Charlie', 'neutral'),
    ('Sophie', 'female'),
    ('Bonnie', 'neutral'),
    ('Jackie', 'neutral'),
    ('Jessie', 'neutral'),
    ('Maggie', 'neutral'),
    ('Robbie', 'neutral'),
    ('Bobby', 'neutral'),
    ('Bobbie', 'neutral'),
    ('Billie', 'neutral'),
    ('Bowie', 'neutral'),
    ('Elvis', 'neutral'),
    ('Frodo', 'neutral'),
    ('Nala', 'female'),
    ('Pluto', 'neutral'),
    ('Blacky', 'neutral'),
    ('Brutus', 'male')
) AS t(name, gender)
ON CONFLICT DO NOTHING;

-- =============================================
-- DUTCH (nl) - Strong / Kort & Stoer
-- Krachtige, korte namen met power
-- =============================================
INSERT INTO public.names (name, gender, set_id)
SELECT name, gender, (SELECT id FROM public.name_sets WHERE language = 'nl' AND style = 'strong' LIMIT 1)
FROM (VALUES
    -- Female strong names
    ('Alice', 'female'),
    ('Amber', 'female'),
    ('Dushi', 'female'),
    ('Fenna', 'female'),
    ('Freya', 'female'),
    ('Nikki', 'female'),
    ('Pippa', 'female'),
    ('Sacha', 'female'),
    ('Sally', 'female'),
    ('Sanne', 'female'),
    ('Sarah', 'female'),
    ('Shiva', 'female'),
    ('Tessa', 'female'),
    ('Tosca', 'female'),
    ('Zorra', 'female'),
    ('Lizzy', 'female'),
    ('Cindy', 'female'),
    ('Faith', 'female'),
    ('Belle', 'female'),
    ('Bente', 'female'),
    ('Donja', 'female'),
    ('Donna', 'female'),
    ('Floor', 'female'),
    ('Indra', 'female'),
    ('Jenna', 'female'),
    ('Kelly', 'female'),
    ('Kiara', 'female'),
    ('Loena', 'female'),
    ('Lotte', 'female'),
    ('Mandy', 'female'),
    ('Milou', 'female'),
    ('Mindy', 'female'),
    ('Missy', 'female'),
    ('Sandy', 'female'),
    ('Sasha', 'female'),
    ('Sasja', 'female'),
    ('Senna', 'female'),
    ('Sonja', 'female'),
    ('Tinka', 'female'),
    ('Zenna', 'female'),
    ('Bibi', 'female'),
    ('Inka', 'female'),
    ('Iris', 'female'),
    ('Lana', 'female'),
    ('Lara', 'female'),
    ('Nina', 'female'),
    ('Noor', 'female'),
    ('Nora', 'female'),
    ('Romy', 'female'),
    ('Roos', 'female'),
    ('Rosa', 'female'),
    ('Rose', 'female'),
    ('Roxy', 'female'),
    ('Ruby', 'female'),
    ('Saar', 'female'),
    ('Sara', 'female'),
    ('Suus', 'female'),
    ('Tess', 'female'),
    ('Yara', 'female'),
    ('Yuna', 'female'),
    ('Zina', 'female'),
    ('Zita', 'female'),
    ('Ziva', 'female'),
    ('Zoey', 'female'),
    ('Zora', 'female'),
    ('Lola', 'female'),
    ('Lucy', 'female'),
    ('Babs', 'female'),
    ('Dana', 'female'),
    ('Demi', 'female'),
    ('Didi', 'female'),
    ('Ella', 'female'),
    ('Hera', 'female'),
    ('Jane', 'female'),
    ('Jill', 'female'),
    ('Kiki', 'female'),
    ('Lena', 'female'),
    ('Lisa', 'female'),
    ('Mira', 'female'),
    ('Nena', 'female'),
    ('Raya', 'female'),
    ('Siba', 'female'),
    ('Sita', 'female'),
    ('Tara', 'female'),
    ('Tyra', 'female'),
    ('Ulla', 'female'),
    ('Xena', 'female'),
    ('Zara', 'female'),
    ('Zena', 'female'),
    ('Zoe', 'female'),
    ('Fien', 'female'),
    ('Pien', 'female'),
    ('Vera', 'female'),
    ('Doris', 'female'),
    ('Joya', 'female'),
    ('Mimi', 'female'),
    ('Nita', 'female'),
    ('Risa', 'female'),
    ('Juli', 'female'),
    ('Kyra', 'female'),
    ('Lia', 'female'),
    ('Gigi', 'female'),
    ('Kiko', 'female'),
    ('Lilo', 'female'),
    ('Loet', 'female'),
    ('Lot', 'female'),
    ('Zia', 'female'),
    ('Rifka', 'female'),
    ('Zus', 'female'),
    ('Filou', 'female'),
    -- Male strong names
    ('Midas', 'male'),
    ('Oscar', 'male'),
    ('Chico', 'male'),
    ('Joris', 'male'),
    ('Pablo', 'male'),
    ('Renzo', 'male'),
    ('Rowan', 'male'),
    ('Scott', 'male'),
    ('Diego', 'male'),
    ('Jason', 'male'),
    ('Benji', 'male'),
    ('Bruce', 'male'),
    ('Bruno', 'male'),
    ('Floyd', 'male'),
    ('Flynn', 'male'),
    ('Harry', 'male'),
    ('Kenzo', 'male'),
    ('Louis', 'male'),
    ('Thor', 'male'),
    ('Bram', 'male'),
    ('Dex', 'male'),
    ('Dean', 'male'),
    ('Duuk', 'male'),
    ('Finn', 'male'),
    ('Gijs', 'male'),
    ('Guus', 'male'),
    ('Hugo', 'male'),
    ('Jip', 'male'),
    ('Joep', 'male'),
    ('Koos', 'male'),
    ('Leo', 'male'),
    ('Mees', 'male'),
    ('Mike', 'male'),
    ('Mick', 'male'),
    ('Moos', 'male'),
    ('Niek', 'male'),
    ('Noud', 'male'),
    ('Otto', 'male'),
    ('Ries', 'male'),
    ('Rik', 'male'),
    ('Roef', 'male'),
    ('Ruud', 'male'),
    ('Siep', 'male'),
    ('Stan', 'male'),
    ('Ted', 'male'),
    ('Teun', 'male'),
    ('Timo', 'male'),
    ('Tom', 'male'),
    ('Toon', 'male'),
    ('Vic', 'male'),
    ('Abe', 'male'),
    ('Alex', 'male'),
    ('Bart', 'male'),
    ('Ben', 'male'),
    ('Bob', 'male'),
    ('Cas', 'male'),
    ('Daan', 'male'),
    ('Job', 'male'),
    ('Kai', 'male'),
    ('Lex', 'male'),
    ('Lyam', 'male'),
    ('Niels', 'male'),
    ('Olaf', 'male'),
    ('Owen', 'male'),
    ('Raf', 'male'),
    ('Reza', 'male'),
    ('Ruben', 'male'),
    ('Silas', 'male'),
    ('Skip', 'male'),
    ('Ties', 'male'),
    ('Gus', 'male'),
    ('Boy', 'male'),
    ('Fos', 'male'),
    ('Jenk', 'male'),
    ('Nils', 'male'),
    ('Shaun', 'male'),
    ('Zoom', 'male'),
    ('Dino', 'male'),
    ('Freek', 'male'),
    ('Rocco', 'male'),
    ('Dolf', 'male'),
    ('Loek', 'male'),
    ('Tobi', 'male'),
    ('Tygo', 'male'),
    ('Vito', 'male'),
    ('Nino', 'male'),
    -- Neutral strong names
    ('Astor', 'neutral'),
    ('Balou', 'neutral'),
    ('Bully', 'neutral'),
    ('Djoek', 'neutral'),
    ('Jerry', 'neutral'),
    ('Kazan', 'neutral'),
    ('Ringo', 'neutral'),
    ('Amigo', 'neutral'),
    ('Chevy', 'neutral'),
    ('Dixie', 'neutral'),
    ('Gismo', 'neutral'),
    ('Milow', 'neutral'),
    ('Candy', 'neutral'),
    ('Chica', 'neutral'),
    ('Akira', 'neutral'),
    ('Angel', 'neutral'),
    ('Astra', 'neutral'),
    ('Baloe', 'neutral'),
    ('Balto', 'neutral'),
    ('Bijou', 'neutral'),
    ('Billy', 'neutral'),
    ('Binky', 'neutral'),
    ('Blitz', 'neutral'),
    ('Bodhi', 'neutral'),
    ('Bonny', 'neutral'),
    ('Boots', 'neutral'),
    ('Britt', 'neutral'),
    ('Budha', 'neutral'),
    ('Butch', 'neutral'),
    ('Darco', 'neutral'),
    ('Devil', 'neutral'),
    ('Dizzy', 'neutral'),
    ('Evita', 'neutral'),
    ('Falco', 'neutral'),
    ('Gipsy', 'neutral'),
    ('Gizmo', 'neutral'),
    ('Gucci', 'neutral'),
    ('Jacky', 'neutral'),
    ('James', 'neutral'),
    ('Jamie', 'neutral'),
    ('Jessy', 'neutral'),
    ('Jimmy', 'neutral'),
    ('Jolly', 'neutral'),
    ('Kayla', 'neutral'),
    ('Kenji', 'neutral'),
    ('Laika', 'neutral'),
    ('Laska', 'neutral'),
    ('Layka', 'neutral'),
    ('Loeka', 'neutral'),
    ('Macho', 'neutral'),
    ('Maylo', 'neutral'),
    ('Micky', 'neutral'),
    ('Milan', 'neutral'),
    ('Nicky', 'neutral'),
    ('Ollie', 'neutral'),
    ('Pinky', 'neutral'),
    ('Pixie', 'neutral'),
    ('Prada', 'neutral'),
    ('Radja', 'neutral'),
    ('Rambo', 'neutral'),
    ('Rebel', 'neutral'),
    ('Ricky', 'neutral'),
    ('Rocky', 'neutral'),
    ('Rover', 'neutral'),
    ('Sammy', 'neutral'),
    ('Sjors', 'neutral'),
    ('Spike', 'neutral'),
    ('Tayco', 'neutral'),
    ('Terry', 'neutral'),
    ('Timmy', 'neutral'),
    ('Tommy', 'neutral'),
    ('Turbo', 'neutral'),
    ('Tyson', 'neutral'),
    ('Wodan', 'neutral'),
    ('Woody', 'neutral'),
    ('Yoshi', 'neutral'),
    ('Ziggy', 'neutral'),
    ('Zorro', 'neutral'),
    ('Indy', 'neutral'),
    ('Noa', 'neutral'),
    ('Bo', 'neutral'),
    ('Dries', 'neutral'),
    ('Jazz', 'neutral'),
    ('Luca', 'neutral'),
    ('Onyx', 'neutral'),
    ('Puk', 'neutral'),
    ('Quinn', 'neutral'),
    ('Zipp', 'neutral'),
    ('Coco', 'neutral'),
    ('Mo', 'neutral'),
    ('Snor', 'neutral'),
    ('Aap', 'neutral'),
    ('Zoef', 'neutral'),
    ('Iggy', 'neutral'),
    ('Muk', 'neutral'),
    ('Mup', 'neutral'),
    ('Riff', 'neutral'),
    ('Riva', 'neutral'),
    ('Trix', 'neutral'),
    ('Mila', 'female'),
    ('Nola', 'female'),
    ('Sofi', 'female'),
    ('Perla', 'female'),
    ('Rox', 'female'),
    ('Diva', 'female'),
    ('Cleo', 'female'),
    ('Vita', 'female'),
    ('Beau', 'male'),
    ('Xavi', 'male'),
    ('Hummer', 'neutral'),
    ('Hunter', 'neutral'),
    ('Chester', 'neutral'),
    ('Dazzle', 'neutral'),
    ('Denzel', 'neutral'),
    ('Banjer', 'neutral'),
    ('Queeny', 'female')
) AS t(name, gender)
ON CONFLICT DO NOTHING;

-- =============================================
-- Summary of corrected categorization
-- =============================================
-- cute: ~60 names - Zachte, knuffelbare namen
-- petnicknames: ~30 names - Echte Nederlandse koosnamen/verkleinwoorden
-- vintage: ~20 names - Ouderwetse opa/oma namen
-- nature: ~25 names - Natuur-gerelateerde namen
-- funny: ~30 names - Grappige, speelse namen
-- classic: ~30 names - Tijdloze klassiekers
-- strong: ~280 names - Korte, krachtige namen
-- 
-- Total: ~475 unique Dutch names
